mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///selection?characterEncoding=utf-8
    username: root
    password: root
  mvc:
    hiddenmethod:
      filter:
        enabled: true